INTEGER IDENTITY

CREATE TABLE CLIENTS (
       CLIENTID             INTEGER IDENTITY,
       THREADID			    INTEGER NOT NULL,
       CLIENTNAME           VARCHAR(24) NOT NULL,
       CLIENTIP             VARCHAR(20) NOT NULL,
       ONLINETIME			VARCHAR(40) NOT NULL,
       PRIMARY KEY (CLIENTID)
);

CREATE TABLE CLIENTMODULES (
       MODULEID             INTEGER IDENTITY,
       THREADID             INTEGER NOT NULL,
       MODULENAME           VARCHAR(24) NOT NULL,
       DISPLAYNAME          VARCHAR(24) NOT NULL,
       DESCRIPTION          VARCHAR(64) NULL,
       MODULETYPE			INTEGER DEFAULT 0,
       CLASSNAME            VARCHAR(128) NOT NULL,
       PRIMARY KEY (MODULEID)
);

CREATE TABLE ARGUEMENTS (
       THREADID             INTEGER NOT NULL,
       MODULEID             INTEGER NOT NULL,
       ARGUEMENT            VARCHAR(32) NOT NULL
);
